name: On PR - Merge to master
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
env:
  NAME: 'CI/CD Env'
on:
  pull_request:
    branches:
      - master
    types:
      - closed
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  on-merge-action:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_CONFIG_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
