name: On PR 'statc/**' - Merge to master
run-name: Deploying static files to S3 🚀
on:
  pull_request:
    branches:
      - master
    types:
      - closed
    paths:
    - 'static/**'
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  on-merge-action:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: prod
    steps:

      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-central-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Upload static files to S3
        run: aws s3 sync static/ $S3_BUCKET_URL
        env:
          S3_BUCKET_URL: ${{ secrets.S3_BUCKET_URI }}

      - name: Invalidate Cloudfront
        run: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
        env:
          CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_ID }}
